//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MULEWcfServiceLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class muleEntities : DbContext
    {
        public muleEntities()
            : base("name=muleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<mapping> mappings { get; set; }
        public virtual DbSet<positioning> positionings { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<sensor> sensors { get; set; }
        public virtual DbSet<sensor_details> sensor_details { get; set; }
        public virtual DbSet<user_group> user_group { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
