//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MULEWcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class sensor_details
    {
        public int sensor_details_id { get; set; }
        public int sensor_id { get; set; }
        public string raw_primary_data { get; set; }
        public string raw_meta_data { get; set; }
    
        public virtual sensor sensor { get; set; }
    }
}
