//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MULEWcfServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class sensor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sensor()
        {
            this.sensor_details = new HashSet<sensor_details>();
        }
    
        public int sensor_id { get; set; }
        public int post_id { get; set; }
        public string avg_primary_data { get; set; }
        public string sem { get; set; }
        public string meta_data { get; set; }
        public byte[] image { get; set; }
    
        public virtual post post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sensor_details> sensor_details { get; set; }
    }
}
